# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='municipio',
        ),
    ]
