# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eees', '0003_remove_colegio_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eees.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eees.Municipio')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('eees.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(choices=[('MANANA', 'MANANA'), ('TARDE', 'TARDE'), ('UNICA', 'UNICA'), ('NOCTURNA', 'NOCTURNA'), ('SABATINA', 'SABATINA')], max_length=200)),
                ('grado', models.CharField(choices=[('PRIMARIA', (('0', 'CERO'), ('1', 'PRIMERO'), ('2', 'SEGUNDO'), ('3', 'TERCERO'), ('4', 'CUARTO'), ('5', 'QUINTO'))), ('SECUNDARIA', (('6', 'SEXTO'), ('7', 'SEPTIMO'), ('8', 'OCTAVO'), ('9', 'NOVENO'), ('10', 'DECIMO'), ('11', 'UNDECIMO')))], max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activar')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eees.Colegio')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eees.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eees.Municipio')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
            bases=('eees.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='manejodatos',
            field=models.BooleanField(default=False, verbose_name='Manejo datos'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eees.Profesor'),
        ),
    ]
