# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eees', '0005_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activar'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activar'),
        ),
    ]
