# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eees', '0007_auto_20170919_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
